- src/main/java/com/example/DoroServer/global/common/BaseResponse.java
- src/main/java/com/example/DoroServer/global/common/ErrorResponse.java
- src/main/java/com/example/DoroServer/global/common/SuccessResponse.java
- src/main/java/com/example/DoroServer/global/exception/BaseException.java
- src/main/java/com/example/DoroServer/global/exception/Code.java
- src/main/java/com/example/DoroServer/global/exception/ErrorCode.java
- src/main/java/com/example/DoroServer/global/exception/ExceptionController.java
- src/main/java/com/example/DoroServer/global/exception/GlobalExceptionHandler.java
PR 타입(하나 이상의 PR 타입을 선택해주세요)
-[] 기능 삭제
-[] 버그 수정
-[] 의존성, 환경 변수, 빌드 관련 코드 업데이트
반영 브랜치
weightsforfun/main -> Doro-server/develop
변경 사항
exception, Success Response 생성
global exception handler 생성
예시를 위한 exception controller 생성
테스트 결과
> Exception handling 기능 구현

- .gitignore
- build.gradle
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/domain/user/repository/UserRepository.java
- src/main/java/com/example/DoroServer/global/config/SecurityConfig.java
- src/main/java/com/example/DoroServer/global/jwt/CustomUserDetailsService.java
- src/main/java/com/example/DoroServer/global/jwt/JwtAuthenticationFilter.java
- src/main/java/com/example/DoroServer/global/jwt/JwtTokenProvider.java
ju-yeop/main -> Doro-Server/develop
> Spring Security

- build.gradle
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/global/config/CorsConfig.java
- src/main/java/com/example/DoroServer/global/config/RedisConfig.java
- src/main/java/com/example/DoroServer/global/config/SecurityConfig.java
- src/main/java/com/example/DoroServer/global/jwt/JwtTokenProvider.java
- src/main/java/com/example/DoroServer/global/jwt/RedisService.java
Ju-Yeop/main -> DOROEDU/develop
- Redis 의존성 추가
- corsFilter 추가
- RedisConfig 추가
- RedisService 추가
- 특정 요청 필터 체인 무시를 위한 메서드 추가 - SecurityConfig
- JwtTokenProvider
-  createRefreshToken 메서드 추가
-  refreshSecretKey 인코딩
> Jwt 수정, Redis 추가

- src/main/java/com/example/DoroServer/domain/announcement/entity/Announcement.java
- src/main/java/com/example/DoroServer/domain/chat/entity/Chat.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/Lecture.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/LectureDate.java
- src/main/java/com/example/DoroServer/domain/lectureContent/entity/LectureContent.java
- src/main/java/com/example/DoroServer/domain/message/entity/Message.java
- src/main/java/com/example/DoroServer/domain/notification/entity/Notification.java
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
BangTtagGum/jun -> Doro-Server/develop
양방향 연관관계 제거, cascade 제거, 멤버변수 Validation 추가
> Entity 연관관계, 멤버변수 수정

- build.gradle
- src/main/java/com/example/DoroServer/domain/lecture/api/LectureApi.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/CreateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesCond.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/UpdateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/Lecture.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepository.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepositoryCustom.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepositoryImpl.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/domain/lectureContent/api/LectureContentApi.java
- src/main/java/com/example/DoroServer/domain/lectureContent/dto/LectureContentDto.java
- src/main/java/com/example/DoroServer/domain/lectureContent/repository/LectureContentRepository.java
- src/main/java/com/example/DoroServer/domain/lectureContent/service/LectureContentService.java
- src/main/java/com/example/DoroServer/domain/user/dto/FindUserRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/api/UserLectureApi.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/CreateTutorReq.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/FindAllTutorsRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/FindMyLecturesRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/SelectTutorReq.java
- src/main/java/com/example/DoroServer/domain/userLecture/entity/TutorStatus.java
- src/main/java/com/example/DoroServer/domain/userLecture/entity/UserLecture.java
- src/main/java/com/example/DoroServer/domain/userLecture/repository/UserLectureRepository.java
- src/main/java/com/example/DoroServer/domain/userLecture/service/UserLectureService.java
- src/main/java/com/example/DoroServer/global/auth/dto/JoinReq.java
- src/main/java/com/example/DoroServer/global/config/ModelMapperConfig.java
- src/main/java/com/example/DoroServer/global/config/QueryDslConfig.java
- src/main/java/com/example/DoroServer/global/exception/ExceptionController.java
ex) weightsforfun/main -> Doro-Server/main
lecture,lectureContent 로직 구현 
querydsl 설정
modelmapper 설정
conflicit 해결
> lecture,lectureContent 로직 구현

- src/main/java/com/example/DoroServer/domain/user/api/UserApi.java
- src/main/java/com/example/DoroServer/domain/user/dto/FindUserRes.java
- src/main/java/com/example/DoroServer/domain/user/dto/UpdateUserReq.java
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/domain/user/repository/UserRepository.java
- src/main/java/com/example/DoroServer/domain/user/service/UserService.java
- src/main/java/com/example/DoroServer/domain/user/service/UserServiceImpl.java
- src/main/java/com/example/DoroServer/global/auth/AuthController.java
- src/main/java/com/example/DoroServer/global/auth/AuthService.java
- src/main/java/com/example/DoroServer/global/auth/AuthServiceImpl.java
- src/main/java/com/example/DoroServer/global/auth/dto/ChangePasswordReq.java
- src/main/java/com/example/DoroServer/global/auth/dto/JoinReq.java
- src/main/java/com/example/DoroServer/global/auth/dto/ReissueReq.java
- src/main/java/com/example/DoroServer/global/auth/dto/SendAuthNumReq.java
- src/main/java/com/example/DoroServer/global/auth/dto/VerifyAuthNumReq.java
- src/main/java/com/example/DoroServer/global/config/SecurityConfig.java
- src/main/java/com/example/DoroServer/global/exception/Code.java
- src/main/java/com/example/DoroServer/global/exception/ExceptionController.java
- src/main/java/com/example/DoroServer/global/jwt/JwtAuthenticationFilter.java
- src/main/java/com/example/DoroServer/global/jwt/JwtTokenProvider.java
- src/main/java/com/example/DoroServer/global/message/MessageServiceImpl.java
- 아이디 찾기 API추가
- 비밀번호 변경 API 추가
- 엑세스 토큰 재발급 API 추가
- 로그아웃 API 추가
- 유저 수정 API 추가
- Jwt Token SecretKey 하나로 통일
- AccessToken 발급, RefreshToken 생성 로직 수정
모든 API 테스트 완료
> Auth 구현 완료, UpdateUser 구현

- src/main/java/com/example/DoroServer/domain/lecture/dto/CreateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesCond.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesRes.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/LectureDto.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/Lecture.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/LectureDate.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepositoryImpl.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/domain/user/api/UserApi.java
- src/main/java/com/example/DoroServer/domain/user/dto/FindAllUsersRes.java
- src/main/java/com/example/DoroServer/domain/user/dto/FindUserRes.java
- src/main/java/com/example/DoroServer/domain/user/service/UserService.java
- src/main/java/com/example/DoroServer/domain/user/service/UserServiceImpl.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/FindAllTutorsRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/FindMyLecturesRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/service/UserLectureService.java
- src/main/java/com/example/DoroServer/global/exception/Code.java
ex) weightforfun/main -> Doro-Server/develop
user 로직 추가
lecture entity 변경 및 로직 추가
ExceptionCode 추가
> user,lecture 로직 추가 및 수정

- src/main/java/com/example/DoroServer/global/auth/AuthController.java
- src/main/java/com/example/DoroServer/global/auth/AuthService.java
- src/main/java/com/example/DoroServer/global/auth/AuthServiceImpl.java
- src/main/java/com/example/DoroServer/global/config/SecurityConfig.java
- src/main/java/com/example/DoroServer/global/exception/Code.java
- src/main/java/com/example/DoroServer/global/jwt/JwtLogoutHandler.java
- 로그아웃 방법 변경 (AuthController Api -> Spring Security Logout)
- 기기 별 Refresh Token 관리 기능 추가
- @Secured 사용 설정
- 로그아웃 테스트 완료
- 기기 별 RefreshToken 포스트맨 테스트 불가능
> 로그아웃 방법 변경, 기기별 리프레시 토큰 관리 기능 추가

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/user/api/UserApi.java
- src/main/java/com/example/DoroServer/domain/user/dto/FindAllUsersRes.java
- src/main/java/com/example/DoroServer/domain/user/dto/FindUserRes.java
- src/main/java/com/example/DoroServer/domain/user/dto/UserMapper.java
- src/main/java/com/example/DoroServer/domain/user/service/UserServiceImpl.java
- src/main/java/com/example/DoroServer/domain/userLecture/service/UserLectureService.java
- src/main/java/com/example/DoroServer/global/config/TestConfig.java
user mapstruct 추가
강의 선정시 알림전송 기능 추가
> 알림전송기능 추가 및 api 수정

- src/main/java/com/example/DoroServer/global/auth/AuthController.java
- src/main/java/com/example/DoroServer/global/jwt/JwtAuthenticationExceptionHandler.java
- src/main/java/com/example/DoroServer/global/jwt/JwtTokenProvider.java
- Ju-yeop/main -> Doro-Server/develop
- AccessToken 만료 시에도 Reissue 가능하도록 수정
- Reissue Api - @Secured 제거 
- 포스트맨 테스트 완료
> Reissue 예외 수정

- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/global/config/ModelMapperConfig.java
column table mapper 삭제안됌 -> 직접 지움으로 수정
ex) weightsforfun/main -> DOROEDU/develop
lecture update 로직 변경
mapstruct config 설정 변경
> Fix: lecture update 로직수정

- src/main/java/com/example/DoroServer/domain/announcement/dto/AnnouncementReq.java
- src/main/java/com/example/DoroServer/domain/announcement/dto/AnnouncementRes.java
- src/main/java/com/example/DoroServer/domain/announcement/entity/Announcement.java
- src/main/java/com/example/DoroServer/domain/announcement/service/AnnouncementService.java
writer 추가로 인한 req, res, service 수정
BangTtagGum/main -> doro/develop
Announcement Entity에 writer 변수 추가
> Announcement Entity writer 변수 추가

- build.gradle
- src/main/java/com/example/DoroServer/domain/announcement/api/AnnouncementApi.java
- src/main/java/com/example/DoroServer/domain/announcement/service/AnnouncementService.java
- src/main/java/com/example/DoroServer/domain/notification/api/NotificationApi.java
- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationContentReq.java
- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationDto.java
- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationReq.java
- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationRes.java
- src/main/java/com/example/DoroServer/domain/notification/entity/Notification.java
- src/main/java/com/example/DoroServer/domain/notification/entity/NotificationType.java
- src/main/java/com/example/DoroServer/domain/notification/repository/NotificationRepository.java
- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/token/repository/TokenRepository.java
- src/main/java/com/example/DoroServer/domain/user/repository/UserRepository.java
- src/main/java/com/example/DoroServer/domain/userNotification/repository/UserNotificationRepository.java
- src/main/java/com/example/DoroServer/domain/userNotification/service/UserNotificationService.java
- src/main/java/com/example/DoroServer/global/exception/Code.java
BangTtagGum/Doro-server/main -> DOROEDU/Doro-Server/develop
FCM 메세지 요청 전송 시 비동기 전송기능 추가, 공지 생성 알림과 기본 발송 알림 구분
> FCM 비동기 전송 기능 추가

- build.gradle
- src/main/java/com/example/DoroServer/DoroServerApplication.java
- src/main/java/com/example/DoroServer/domain/user/api/UserApi.java
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/domain/user/repository/UserRepository.java
- src/main/java/com/example/DoroServer/domain/user/service/UserService.java
- src/main/java/com/example/DoroServer/domain/user/service/UserServiceImpl.java
- src/main/java/com/example/DoroServer/global/auth/dto/JoinReq.java
- src/main/java/com/example/DoroServer/global/config/CorsConfig.java
- 휴먼계정 스케줄러 구현
- UserEntity - isActive Column 추가
- Cors 코드 수정
> 휴먼계정 판단 스케줄러 추가, Cors 에러 해결

- src/main/java/com/example/DoroServer/domain/announcement/api/AnnouncementApi.java
- src/main/java/com/example/DoroServer/domain/announcement/dto/AnnouncementReq.java
- src/main/java/com/example/DoroServer/domain/notification/api/NotificationApi.java
- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationContentReq.java
- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationRes.java
- src/main/java/com/example/DoroServer/domain/notification/entity/Notification.java
- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/global/auth/dto/JoinReq.java
BangTtagGum/Doro-Server/main -> Doro-Server/develop
User Entity의 notificationAgreement,
AnnouncementReq Dto의 writer에 Validation 추가
.
> Validation 추가 및 공지, 알림 메소드 인가 처리 , 알림 조회시 해당하는 공지 id 값 반환

- src/main/java/com/example/DoroServer/domain/lecture/api/LectureApi.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/CreateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesCond.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesRes.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/LectureDto.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/UpdateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/Lecture.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/LectureDate.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepository.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepositoryImpl.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/FindAllTutorsRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/service/UserLectureService.java
weightsforfun/main -> Doro-Server/develop
Lecture entity 및 dto 날짜 관련 필드 LocalDate로 변경
프론트엔드 알람 전송 오류관련 이슈 임시조치
신청강사 조회 dto 수정
강의 마지막 회차 종료시 스케줄링을 통한 Status FINISHED 로 자동 변경 로직 추가 
PostMan 및 workBench 로 테스트 , 추후 테스트 코드 작성 예정
> Fix: 강의 날짜 관련 필드 타입 변경,강의 Status 변경 기능 추가 , 프론트 엔드 이슈 임시조치

- .gitignore
- src/main/java/com/example/DoroServer/domain/announcement/api/AnnouncementApi.java
- src/main/java/com/example/DoroServer/domain/announcement/dto/AnnouncementMultipartReq.java
- src/main/java/com/example/DoroServer/domain/token/repository/TokenRepository.java
- src/main/java/com/example/DoroServer/domain/userLecture/repository/UserLectureRepository.java
- src/main/java/com/example/DoroServer/domain/userNotification/repository/UserNotificationRepository.java
- src/main/java/com/example/DoroServer/global/auth/AuthServiceImpl.java
- src/main/java/com/example/DoroServer/global/config/SecurityConfig.java
- src/main/java/com/example/DoroServer/global/jwt/JwtLogoutHandler.java
- src/main/java/com/example/DoroServer/global/jwt/JwtLogoutSuccessHandler.java
- 회원탈퇴 시 관련 데이터 전체 삭제 로직 추가
- 로그아웃 리다이렉트 비활성화
- 공지생성 V2 / V3 추가
- .gitignore - MockSSL 파일 추가
Postman 테스트 모두 통과!
> Feat: 회원탈퇴 시 관련 데이터 전체 삭제 로직 추가, 로그아웃 리다이렉트 비활성화, 공지생성 V2 / V3 추가

- .gitignore
- build.gradle
- src/main/java/com/example/DoroServer/domain/lecture/api/LectureApi.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindLectureRes.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/LectureMapper.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/domain/lectureContent/dto/LectureContentDto.java
- src/main/java/com/example/DoroServer/domain/lectureContent/dto/UpdateLectureContentReq.java
- src/main/java/com/example/DoroServer/domain/lectureContent/entity/LectureContent.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/FindAllAssignedTutorsRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/UserLectureMapper.java
- src/main/java/com/example/DoroServer/domain/userLecture/repository/UserLectureRepository.java
ex) weightsforfun/main -> DOROEDU/develop
선정된 강사 다른 강사 조회 가능 로직 추가
JACOCO 의존성 설정 
postman으로 테스트 완료
> Feat: 선정된 강사 다른 강사 조회 로직 추가, jacoco 의존성 추가

- src/main/java/com/example/DoroServer/domain/announcement/api/AnnouncementApi.java
- src/main/java/com/example/DoroServer/domain/announcement/entity/Announcement.java
- src/main/java/com/example/DoroServer/domain/announcement/service/AnnouncementService.java
- src/main/java/com/example/DoroServer/domain/chat/entity/Chat.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/Lecture.java
- src/main/java/com/example/DoroServer/domain/lectureContent/entity/LectureContent.java
- src/main/java/com/example/DoroServer/domain/message/entity/Message.java
- src/main/java/com/example/DoroServer/domain/notification/entity/Notification.java
- src/main/java/com/example/DoroServer/domain/token/entity/Token.java
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/domain/userChat/entity/UserChat.java
- src/main/java/com/example/DoroServer/domain/userLecture/entity/UserLecture.java
- src/main/java/com/example/DoroServer/domain/userNotification/entity/UserNotification.java
- src/main/java/com/example/DoroServer/global/auth/AuthController.java
- src/main/java/com/example/DoroServer/global/util/annotation/ClearSecurityContext.java
- src/main/java/com/example/DoroServer/global/util/aspect/SecurityContextAspect.java
- Ju-yeop/main -> Doro-Server/develop
- 시큐리티 컨텍스트 홀더 초기화 AOP 추가
- GeneratedValue 전략 선정
- 공지 생성/수정 API 리팩토링
- 포스트맨, 워크벤치 테스트 완료
> 시큐리티 컨텍스트 홀더 초기화 AOP 추가, GeneratedValue 전략 선정, 공지 생성/수정 API 리팩토링

- src/main/java/com/example/DoroServer/domain/lecture/dto/CreateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesCond.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/LectureDto.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepository.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/test/java/com/example/DoroServer/domain/lectureContent/service/LectureContentServiceTest.java
ex) weightsforfun/main -> DOROEDU/develop
jacoco 의존성 추가
LectureContent Service 테스트코드 완성
LectureService 리팩토링 및 프론트 건의 사항 수정
postman 테스트 완료
> Feat: 테스트 코드 작성, 프론트 엔드 건의사항 반영 및 리팩토링

- build.gradle
- lombok.config
test 실행시 report,verification 자동 실행
어노테이션, QEntity ,DTO 디렉토리, Exception 디렉토리 ,Main
테스트 커버리지에서 제외
jacoco build 파일 확인
> Fix: Jacoco 설정 변경

- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/CreateTutorReq.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/SelectTutorReq.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/UserLectureMapper.java
- src/main/java/com/example/DoroServer/domain/userLecture/repository/UserLectureRepository.java
- src/main/java/com/example/DoroServer/domain/userLecture/service/UserLectureService.java
- src/test/java/com/example/DoroServer/domain/lecture/service/LectureServiceTest.java
- src/test/java/com/example/DoroServer/domain/lectureContent/service/LectureContentServiceTest.java
- src/test/java/com/example/DoroServer/domain/userLecture/service/UserLectureServiceTest.java
weigthsforfun/main -> DOROEDU/develop
lecture mapper 오타수정
lecture service 테스트 코드 작성
postman으로 확인
jacoco 로 커버리지 93% 확인
> Test:  lecture service 테스트 코드 작성

- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/CreateTutorReq.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/FindMyLecturesRes.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/SelectTutorReq.java
- src/main/java/com/example/DoroServer/domain/userLecture/dto/UserLectureMapper.java
- src/main/java/com/example/DoroServer/domain/userLecture/repository/UserLectureRepository.java
- src/test/java/com/example/DoroServer/domain/lecture/repository/LectureRepositoryTest.java
- src/test/java/com/example/DoroServer/domain/lecture/service/LectureServiceTest.java
weigthsforfun/main -> DOROEDU/develop
userLecture DTO 수정
lectureDates 추가
NoArgsConstructor, AllArgsConstructor 어노테이션 추가
delete Lecture 로직 변경
테스트 코드 수정
postman으로 테스트 완료
> Feat: userLecture DTO 수정 및 어노테이션 추가

- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationDto.java
- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/user/service/UserServiceImpl.java
BangTtagGum/Doro-server/main -> DOROEDU/Doro-Server/develop
NotificaionDto 객체 Data 필드 수정
테스트 이상 없음
> FCM 서버로 보낼 NotificationDto 필드 변수 수정

- build.gradle
- src/main/java/com/example/DoroServer/global/auth/AuthServiceImpl.java
- src/main/java/com/example/DoroServer/global/auth/dto/ChangePasswordReq.java
- src/main/java/com/example/DoroServer/global/auth/dto/JoinReq.java
- src/main/java/com/example/DoroServer/global/auth/dto/LoginReq.java
- src/test/java/com/example/DoroServer/global/auth/AuthControllerTest.java
- src/test/java/com/example/DoroServer/global/auth/AuthServiceImplTest.java
- src/test/java/com/example/DoroServer/global/auth/AuthTestSetup.java
- Feat: 휴대폰 중복 체크 로직 주석 제거
- AuthServiceImplTest 완료
- AuthControllerTest 추가
- Test 롬복 사용 의존성 추가
> Feat: 휴대폰 중복 체크 로직 주석 제거, AuthServiceImplTest 완료, AuthControllerTest 추가

- src/main/java/com/example/DoroServer/domain/lecture/api/LectureApi.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesCond.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesInfo.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesRes.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/LectureMapper.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepository.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepositoryImpl.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/test/java/com/example/DoroServer/domain/lecture/service/LectureServiceTest.java
모든강의 조회 로직 수정
status 로 강의 리스트 구분
전체 강의수 추가
교육 지역 목록 조회 api추가
postman으로 테스트
> 모든 강의 조회 요구사항 수정 반영

- src/main/java/com/example/DoroServer/domain/lecture/api/LectureApi.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/CreateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/FindAllLecturesInfo.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/LectureDto.java
- src/main/java/com/example/DoroServer/domain/lecture/dto/UpdateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/entity/Lecture.java
- src/main/java/com/example/DoroServer/domain/lecture/repository/LectureRepository.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/domain/lectureContent/dto/LectureContentDto.java
- src/main/java/com/example/DoroServer/domain/lectureContent/dto/UpdateLectureContentReq.java
- src/main/java/com/example/DoroServer/domain/lectureContent/entity/LectureContent.java
- src/test/java/com/example/DoroServer/domain/lecture/service/LectureServiceTest.java
- src/test/java/com/example/DoroServer/domain/lectureContent/service/LectureContentServiceTest.java
- src/test/java/com/example/DoroServer/domain/userLecture/repository/UserLectureRepositoryTest.java
기타 사항 lecture content 에서 lecture 로 수정
entity, DTO, test code 변경
도시조회 강의 상태별 조회로 로직 변경
postman 및 테스트 코드로 테스트 통과
> Feat:  요구사항 변경 반영

- src/main/java/com/example/DoroServer/domain/lecture/dto/UpdateLectureReq.java
- src/main/java/com/example/DoroServer/domain/lecture/service/LectureService.java
- src/main/java/com/example/DoroServer/global/config/ModelMapperConfig.java
wiehgtsforfun/main -> DOROEDU/develop
강의 컨텐츠 수정 로직 추가
modelMapper 설정 변경
lectureUpdate 로직 변경
UpdateLectureReq 수정
postman 및 테스트 코드로 테스트 통과
> Feat: 강의 컨텐츠 수정 로직 추가

- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/global/auth/dto/JoinReq.java
> Fix: 생년월일 선택 사항으로 변경

- src/main/java/com/example/DoroServer/domain/user/dto/UpdateUserReq.java
- src/main/java/com/example/DoroServer/domain/user/entity/User.java
- src/main/java/com/example/DoroServer/domain/user/service/UserServiceImpl.java
회원가입 시 생년월일 입력이 선택사항으로 바뀜에 따라 생년월일 수정 가능하도록 변경
NULL 값 테스트 포함 포스트맨 테스트 완료
> Feat: 유저 생년월일 수정 가능

- .github/workflows/deploy.yml
Deploy.yml - 워크플로우 파일 수정 - Json 생성 방식 변경 - 라이브러리 사용
> Fix: Deploy.yml Json 파일 생성 방식 변경

- .github/workflows/deploy.yml
Deploy.yml - 워크플로우 파일 수정 - Json 생성 경로 수정
> Fix: deploy.yml Json 생성 경로 변경

- .github/workflows/deploy.yml
Deploy.yml - 워크플로우 파일 수정 - Json 생성 경로 수정
> Fix: deploy.yml json 파일 생성 경로 변경

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
배포 서버 로그 확인 - NotificationService 로그 추가
> Style: NotificationService 배포 서버 로그 확인

- .github/workflows/deploy.yml
- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
Doro-Server/hotfix -> Doro-Server/develop
- deploy.yml firbase_service_key.json 파일 생성 방식 변경
- NotificationService 로그 주석 해제
> Fix: deploy.yml Json 파일 생성 오류 해결

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/user/repository/UserRepository.java
- findAllWithTokens 수정 - INNER JOIN
- NotificationService - sendNotificationToAll 메서드 로직 수정
> Fix: Notification 오류 해결

- docker-compose.blue.yml
- docker-compose.green.yml
Doro-Server/deploy -> Doro-Server/main
> Fix: 알림 오류 해결

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
> Fix: 알림 전송 모두 실패 시 Notification 튜플 삭제하는 로직 제거

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/user/repository/UserRepository.java
Doro-Server/develop -> Doro-Server/main
> Fix: 알림 전송 모두 실패 시 Notification 튜플 삭제하는 로직 제거 

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
Doro-Server/develop -> Doro-Server/main
> Fix: 알림 발송 시 알림을 DB에서 찾을 수 없다는 오류 해결

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/notification/service/SaveNotificationService.java
트랜잭션 프록시 내부 호출 문제 해결을 위한 클래스 분리
> Fix: saveNotificationService 클래스 분리

- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
> Fix: user_notification 유저 당 하나씩만 생성 되도록 변경

- src/main/java/com/example/DoroServer/domain/notification/service/SaveNotificationService.java
> Fix: Not found notification 에러 해결

- .github/ISSUE_TEMPLATE/feature-request.md
> Docs: 이슈 템플릿 추가

- src/main/java/com/example/DoroServer/domain/lecture/api/LectureApi.java
- src/main/java/com/example/DoroServer/domain/lectureContent/api/LectureContentApi.java
- src/main/java/com/example/DoroServer/domain/userLecture/api/UserLectureApi.java
매니저 전용 API 보안 설정
개인용 API 타유저 접근 금지 보안 설정
lecture, userLecture 도메인 API 계층에 인가 기능 전부 추가
postman 을 통한 접근 허용, 접근 금지 테스트 완료
> Feat: userLectrue, Lecture 도메인 API 보안 설정

- src/main/java/com/example/DoroServer/domain/userLecture/api/UserLectureApi.java
- src/main/java/com/example/DoroServer/domain/userLecture/repository/UserLectureRepository.java
- src/main/java/com/example/DoroServer/domain/userLecture/service/UserLectureService.java
- src/main/java/com/example/DoroServer/global/exception/Code.java
- src/test/java/com/example/DoroServer/domain/userLecture/service/UserLectureServiceTest.java
강의 신청 API 인가 로직 오류 수정
강의 삭제 API 인가 로직 변경 및 추가
ex) weightsforfun/hotfix -> DOROEDU/hotfix
강의 신청, 삭제 인가 로직 오류 수정 및 변경했습니다.
Postman으로 전부 테스트 완료했습니다.
> Fix: API 인가 로직 변경

- src/main/java/com/example/DoroServer/domain/announcement/api/AnnouncementApi.java
- src/main/java/com/example/DoroServer/domain/announcement/service/AnnouncementService.java
- src/main/java/com/example/DoroServer/domain/notification/api/NotificationApi.java
- src/main/java/com/example/DoroServer/domain/notification/dto/NotificationContentReq.java
- src/main/java/com/example/DoroServer/domain/notification/entity/NotificationType.java
- src/main/java/com/example/DoroServer/domain/notification/service/NotificationService.java
- src/main/java/com/example/DoroServer/domain/notification/service/NotificationServiceRefact.java
- src/main/java/com/example/DoroServer/domain/token/service/TokenService.java
- src/main/java/com/example/DoroServer/domain/userLecture/service/UserLectureService.java
- src/main/java/com/example/DoroServer/domain/userNotification/api/UserNotificationAPI.java
- src/main/java/com/example/DoroServer/global/jwt/JwtLogoutHandler.java
weightsforfun/94-refact-알림-도메인 -> DOROEDU/94-refact-알림-도메인
강의 선정, 공지 등록시 자동 알림 전송 기능 추가
로그아웃이 topic 관리 기능 추가
관련 issue #94 
postman 으로 새로 추가한 기능들 테스트 완료
> Feat: 자동 알림 전송 기능 및 topic 관리 로직 추가

- src/main/java/com/example/DoroServer/global/auth/AuthController.java
- src/main/java/com/example/DoroServer/global/auth/AuthService.java
- src/main/java/com/example/DoroServer/global/auth/AuthServiceImpl.java
- src/main/java/com/example/DoroServer/global/config/SecurityConfig.java
- src/main/java/com/example/DoroServer/global/jwt/JwtAccessDeniedHandler.java
- src/main/java/com/example/DoroServer/global/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/com/example/DoroServer/global/jwt/JwtAuthenticationFilter.java
- src/main/java/com/example/DoroServer/global/jwt/JwtLogoutHandler.java
- src/main/java/com/example/DoroServer/global/jwt/JwtTokenProvider.java
Ju-yeop/102-refact-security -> Doro-Server/develop
- log: info -> debug
- 로그인, 재발급 API 서비스 계층으로 이동
- 토큰 유효성 검사 로직 분리
- validateToken
- validateRefreshToken
- web.ignoring 제외, 모든 요청 인증 필요하도록 변경
> Refact: 스프링 시큐리티 파트 리팩터링 #102
